sudo: required

services:
  - docker

language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - "docker-compose up -d postgres"
  - "sleep 15"
  - "docker-compose up -d"
  - "sleep 15"
  - "curl http://localhost:4000"

before_script:
  - npm run gulp
